version: '3.8'
services:
  db:
    image: postgres:8.0
    container_name: Nexus Project
    restart: unless-stopped
    environment:
      POSTGRES_ROOT_PASSWORD: Bj6Hr5Lv0r3ipUi0
      POSTGRES_DB: Nexus Project
      POSTGRES_USER: rxqgkieocmbjmtgofdlp
      POSTGRES_PASSWORD: Bj6Hr5Lv0r3ipUi0
    ports:
      - "5432:5432"
    volumes:
      - nexus_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  app:
    build: .
    container_name: nexus_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://rxqgkieocmbjmtgofdlp:Bj6Hr5Lv0r3ipUi0@db:5432/Nexus Project
      JWT_SECRET: jHdNNLQWixvgvVIFlqAXZq3p0gIScgbkdgaqkY/rFYzGg08G32dps5seH7pOBMFCJuqq2E0b3WpvHJknUfqxOA==
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: nexus-nextauth-secret-change-in-prod
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy

volumes:
  nexus_db_data:
